name: Build IPTV App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Extract ZIP
      # هذا الأمر سيفك ضغط أي ملف zip موجود في المستودع
      run: unzip -q *.zip -d app_source

    - name: Build APK
      run: |
        # البحث التلقائي عن مسار المشروع داخل المجلد المفكوك
        PROJECT_DIR=$(dirname $(find app_source -name "gradlew" | head -n 1))
        cd $PROJECT_DIR
        
        # إعطاء صلاحية التشغيل للملف وبناء التطبيق
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DhiQar-TV-APK
        # سحب ملف الـ APK النهائي بعد انتهاء البناء
        path: app_source/**/app/build/outputs/apk/debug/*.apk
        
